/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPlayersFromDiscriminatorValue, serializePlayers, type Players } from '../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /players
 */
export interface PlayersRequestBuilder extends BaseRequestBuilder<PlayersRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<PlayersRequestBuilderDeleteQueryParameters> | undefined) : Promise<void>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Players[]>}
     */
     get(requestConfiguration?: RequestConfiguration<PlayersRequestBuilderGetQueryParameters> | undefined) : Promise<Players[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     patch(body: Players, requestConfiguration?: RequestConfiguration<PlayersRequestBuilderPatchQueryParameters> | undefined) : Promise<void>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     post(body: Players, requestConfiguration?: RequestConfiguration<PlayersRequestBuilderPostQueryParameters> | undefined) : Promise<void>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<PlayersRequestBuilderDeleteQueryParameters> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<PlayersRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: Players, requestConfiguration?: RequestConfiguration<PlayersRequestBuilderPatchQueryParameters> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: Players, requestConfiguration?: RequestConfiguration<PlayersRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
export interface PlayersRequestBuilderDeleteQueryParameters {
    createdAt?: string;
    id?: string;
    name?: string;
    telegramId?: string;
}
export interface PlayersRequestBuilderGetQueryParameters {
    createdAt?: string;
    id?: string;
    /**
     * Limiting and Pagination
     */
    limit?: string;
    name?: string;
    /**
     * Limiting and Pagination
     */
    offset?: string;
    /**
     * Ordering
     */
    order?: string;
    /**
     * Filtering Columns
     */
    select?: string;
    telegramId?: string;
}
export interface PlayersRequestBuilderPatchQueryParameters {
    createdAt?: string;
    id?: string;
    name?: string;
    telegramId?: string;
}
export interface PlayersRequestBuilderPostQueryParameters {
    /**
     * Filtering Columns
     */
    select?: string;
}
/**
 * Uri template for the request builder.
 */
export const PlayersRequestBuilderUriTemplate = "{+baseurl}/players{?createdAt*,id*,limit*,name*,offset*,order*,select*,telegramId*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const PlayersRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: PlayersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, application/vnd.pgrst.object+json;nulls=stripped, application/vnd.pgrst.object+json, text/csv",
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: PlayersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, application/vnd.pgrst.object+json, application/vnd.pgrst.object+json;nulls=stripped",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createPlayersFromDiscriminatorValue,
    },
    patch: {
        uriTemplate: PlayersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, application/vnd.pgrst.object+json;nulls=stripped, application/vnd.pgrst.object+json, text/csv",
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/vnd.pgrst.object+json;nulls=stripped",
        requestBodySerializer: serializePlayers,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
    post: {
        uriTemplate: PlayersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, application/vnd.pgrst.object+json;nulls=stripped, application/vnd.pgrst.object+json, text/csv",
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/vnd.pgrst.object+json;nulls=stripped",
        requestBodySerializer: serializePlayers,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
